name: menu_app

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  flutter_paypal: ^0.2.1
  cupertino_icons: ^1.0.2  
  provider: ^6.1.1
  badges: ^3.0.0
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/coffee.jpg
    - assets/images/tea.jpg
    - assets/images/pie.jpg
    - assets/images/pizza.jpg
